name: "GCP Authentication"
description: "Authenticates with GCP using a service account key from secrets"

inputs:
  gcp_service_account_key:
    required: true
    description: "Base64 encoded GCP service account key"
  project_id:
    required: true
    description: "GCP Project ID"

outputs:
  credentials_file:
    description: "Path to the credentials JSON file"
    value: ${{ steps.auth.outputs.credentials_file }}

runs:
  using: "composite"
  steps:
    - name: Set up GCP credentials
      id: auth
      shell: bash
      run: |
        echo "Setting up GCP authentication with Service Account Key..."

        if [ -z "${{ inputs.gcp_service_account_key }}" ]; then
            echo "GCP_SERVICE_ACCOUNT_KEY is not set!"
            exit 1
        fi

        # Decode the service account key and save it to credentials.json
        echo "${{ inputs.gcp_service_account_key }}" | base64 -d > credentials.json

        # Set environment variable for the credentials file
        echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/credentials.json" >> $GITHUB_ENV
        echo "credentials_file=$PWD/credentials.json" >> $GITHUB_OUTPUT

        echo "GCP authentication setup complete."

    - name: Authenticate with gcloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ inputs.gcp_service_account_key }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ inputs.project_id }}

    - name: Test credentials
      shell: bash
      run: |
        echo "Testing credentials..."
        gcloud projects describe "${{ inputs.project_id }}" --format="value(projectNumber)"
        echo "GCP authentication test complete."
