name: Terraform with Approval
run-name: Terraform Plan and Apply with Manual Approval

on:
  workflow_call:
    inputs:
      working_directory:
        description: "Working directory for Terraform"
        required: false
        type: string
        default: "."
      tf_version:
        description: "Terraform version"
        required: false
        type: string
        default: "1.12.2"
      approvers:
        description: "Comma-separated list of GitHub usernames who can approve"
        required: true
        type: string
      minimum_approvals:
        description: "Minimum number of approvals required"
        required: false
        type: number
        default: 1
      approval_timeout_minutes:
        description: "Timeout for approval in minutes"
        required: false
        type: number
        default: 60
    secrets:
      pat_token:
        description: "GitHub Personal Access Token for Terraform GitHub provider"
        required: true
      github_owner:
        description: "GitHub organization/owner name"
        required: true
      gcp_service_account_key:
        description: "GCP service account key (only needed if using GCS backend)"
        required: false

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.plan.outputs.has_changes }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Terraform Plan
        id: plan
        uses: NationalServicesGroup/nsg-github-actions/terraform-plan-github@main
        with:
          working_directory: ${{ inputs.working_directory }}
          tf_version: ${{ inputs.tf_version }}
          gcp_service_account_key: ${{ secrets.gcp_service_account_key }}
          github_token: ${{ secrets.pat_token }}
          github_owner: ${{ secrets.github_owner }}

      - name: Format and Comment Plan
        uses: NationalServicesGroup/nsg-github-actions/terraform-plan-comment@main
        with:
          plan_file: ${{ inputs.working_directory }}/plan_output.txt
          working_directory: ${{ inputs.working_directory }}
          github_token: ${{ secrets.pat_token }}

      - name: Upload Plan Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: |
            ${{ inputs.working_directory }}/tfplan
            ${{ inputs.working_directory }}/plan_output.txt
          retention-days: 1

  manual-approval:
    name: Manual Approval
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.ref == 'refs/heads/main' && needs.terraform-plan.outputs.has_changes == 'true'

    steps:
      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan

      - name: Format Plan for Approval
        id: format-plan
        uses: NationalServicesGroup/nsg-github-actions/terraform-format-plan@main
        with:
          plan_file: plan_output.txt

      - name: Request Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.pat_token }}
          approvers: ${{ inputs.approvers }}
          minimum-approvals: ${{ inputs.minimum_approvals }}
          issue-title: "🚀 Terraform Apply Approval for ${{ github.repository }}"
          issue-body: |
            ## Terraform Apply Approval Required

            **Repository:** ${{ github.repository }}
            **Branch:** ${{ github.ref_name }}
            **Workflow:** ${{ github.workflow }}
            **Run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            ### Proposed Changes

            ```hcl
            ${{ steps.format-plan.outputs.plan_formatted }}
            ```

            ---

            **Approve this issue** to proceed with `terraform apply`.
          exclude-workflow-initiator-as-approver: false
          timeout-minutes: ${{ inputs.approval_timeout_minutes }}

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: [terraform-plan, manual-approval]
    if: github.ref == 'refs/heads/main' && needs.terraform-plan.outputs.has_changes == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: ${{ inputs.working_directory }}

      - name: Run Terraform Apply
        uses: NationalServicesGroup/nsg-github-actions/terraform-apply-github@main
        with:
          working_directory: ${{ inputs.working_directory }}
          tf_version: ${{ inputs.tf_version }}
          gcp_service_account_key: ${{ secrets.gcp_service_account_key }}
          github_token: ${{ secrets.pat_token }}
          github_owner: ${{ secrets.github_owner }}
          plan_file: "tfplan"
